module decode_wb_stage (
    // Clock and Reset
    input wire clk,
    input wire rst,
    
    // Instruction Fields (ra and rb) from IF/ID Register
    input wire [1:0] ra,
    input wire [1:0] rb,
    



    // Write Data Mux Inputs (write back stage signals) from MEM/WB Register
    input wire signed [7:0] alu_out,           // 1. Output from ALU
    input wire signed [7:0] mem_out,           // 2. Data read from Memory 
    input wire signed [7:0] in_port,           // 3. Data from IN.PORT
    input wire signed [7:0] imm,               // 4. Immediate value (LDM instruction) (IR)
    
    // Write Address Mux Inputs (from MEM/WB Register)
    input wire [1:0] ra_i,              // 1. ra of Current instruction IR[1:0]
    input wire [1:0] rb_i,              // 2. rb of Current instruction IR[3:2]




    // DECODE STAGE 
    input wire       rb_e,              // 3. rb stored signal for 2 byte instructions    
  

    // Control Signals decode stage
    input wire  Sel_ReadAddr2,     // 1-bit: 0=ra, 1=rb

    
    // control signals write back stage
    input wire [1:0] Sel_WriteData,     // 2-bit: selects the 8-bit data source
    input wire [1:0] Sel_WriteAddr,     // 2-bit: selects the 2-bit address source
    


    
    // Register File Control (Passed directly or generated by Control Unit)
    input wire wr_en,
    input wire SP_Inc,      // from decode stage pop
    input wire SP_Dec,      // from write back stage push

    // Outputs
    output wire [7:0] rd_data1,         // Read Data 1 output
    output wire [7:0] rd_data2,         // Read Data 2 output
    output wire [7:0] SP_Out,            // Stack Pointer (R3) output

    output wire signed [7:0] DATA_OUT,

    output wire [7:0] RTI_SP           // Output current SP value for RTI and RET instructions

);

    // Internal Wires 
    wire [1:0] mux_rd_addr2;
    
    // Internal Registers 
    reg signed [7:0] mux_wr_data;
    reg [1:0] mux_wr_addr;
    reg [1:0] rb_t;              // 3. rb stored for 2 byte instructions
    


    // 2. Read Address 2 Mux // decode stage
    assign mux_rd_addr2 = Sel_ReadAddr2 ? rb : rb_t;

    assign DATA_OUT = mux_wr_data;
    
    // 3. Write Data Mux 
    always @(*) begin
        case (Sel_WriteData)
            2'b00: mux_wr_data = alu_out;
            2'b01: mux_wr_data = mem_out;
            2'b10: mux_wr_data = in_port;
            2'b11: mux_wr_data = imm;
            default: mux_wr_data = alu_out ;
        endcase
    end
    
    // 4. Write Address Mux (3-to-1)
    always @(*) begin
        case (Sel_WriteAddr)
            2'b00: mux_wr_addr = ra_i;
            2'b01: mux_wr_addr = rb_i;
            2'b10: mux_wr_addr = rb_t;
            default: mux_wr_addr = ra_i; 
        endcase
    end

    // Instantiation of the Register File module (U_RF)
    Register_File U_RF (
        .clk        (clk),
        .rst        (rst),
        .wr_en      (wr_en),
        .wr_addr    (mux_wr_addr),    // Connects Mux output (reg)
        .wr_data    (mux_wr_data),    // Connects Mux output (reg)
        .rd_addr1   (ra),   
        .rd_data1   (rd_data1),   

        .rd_addr2   (mux_rd_addr2),   // Connects Mux output (wire)
        .rd_data2   (rd_data2),  

        .SP_Inc     (SP_Inc),
        .SP_Dec     (SP_Dec),
        .SP         (SP_Out),
        .RTI_SP     (RTI_SP)         
    );

    // Store rb into rb_t in 2 byte instructions 
    always @(posedge clk) 
    begin
        if(rb_e)
            rb_t <= rb;
    end

    


endmodule


